In [30]:
import pandas as pd
import json

In [31]:
df = pd.read_json("all_pokemon.json")

df.head(3)

,abilities,base_experience,cries,forms,game_indices,height,held_items,id,is_default,location_area_encounters,...,order,past_abilities,past_types,species,sprites,stats,types,weight,ranking,popularity
0,"[overgrow, chlorophyll]",64.0,{'latest': 'https://raw.githubusercontent.com/...,"[{'name': 'bulbasaur', 'url': 'https://pokeapi...","[{'game_index': 153, 'version': {'name': 'red'...",7.0,[],1.0,1.0,https://pokeapi.co/api/v2/pokemon/1/encounters,...,1.0,"[{'abilities': [{'ability': None, 'is_hidden':...",[],"{'name': 'bulbasaur', 'url': 'https://pokeapi....",{'back_default': 'https://raw.githubuserconten...,"{'hp': 45, 'attack': 49, 'defense': 49, 'speci...","{'type1': 'grass', 'type2': 'poison'}",69.0,28.0,72.8%
1,"[overgrow, chlorophyll]",142.0,{'latest': 'https://raw.githubusercontent.com/...,"[{'name': 'ivysaur', 'url': 'https://pokeapi.c...","[{'game_index': 9, 'version': {'name': 'red', ...",10.0,[],2.0,1.0,https://pokeapi.co/api/v2/pokemon/2/encounters,...,2.0,"[{'abilities': [{'ability': None, 'is_hidden':...",[],"{'name': 'ivysaur', 'url': 'https://pokeapi.co...",{'back_default': 'https://raw.githubuserconten...,"{'hp': 60, 'attack': 62, 'defense': 63, 'speci...","{'type1': 'grass', 'type2': 'poison'}",130.0,56.0,70.7%
2,[shed-skin],72.0,{'latest': 'https://raw.githubusercontent.com/...,"[{'name': 'metapod', 'url': 'https://pokeapi.c...","[{'game_index': 124, 'version': {'name': 'red'...",7.0,[],11.0,1.0,https://pokeapi.co/api/v2/pokemon/11/encounters,...,15.0,[],[],"{'name': 'metapod', 'url': 'https://pokeapi.co...",{'back_default': 'https://raw.githubuserconten...,"{'hp': 50, 'attack': 20, 'defense': 55, 'speci...","{'type1': 'bug', 'type2': None}",99.0,909.0,36%

In [32]:
df.columns

Index(['abilities', 'base_experience', 'cries', 'forms', 'game_indices',
       'height', 'held_items', 'id', 'is_default', 'location_area_encounters',
       'moves', 'name', 'order', 'past_abilities', 'past_types', 'species',
       'sprites', 'stats', 'types', 'weight', 'ranking', 'popularity'],
      dtype='object')

In [33]:
df_stats = pd.json_normalize(df["stats"])
df_types = pd.json_normalize(df["types"])

df_stats["id"] = df["id"]
df_types["id"] = df["id"]

In [34]:
data = []

for indice in range(len(df["abilities"])):
    habilidades = df["abilities"][indice]
    id = df["id"][indice]
    if not habilidades:
        fila = {"hab_1": None, "id": id}
        data.append(fila)
        continue
    
    if len(habilidades) == 1:
        fila = {"hab_1": habilidades[0], "id": id}
        data.append(fila)

    if len(habilidades) == 2:
        fila = {"hab_1": habilidades[0],"hab_2": habilidades[1],"id": id}
        data.append(fila)

    if len(habilidades) == 3:
        fila = {"hab_1": habilidades[0],"hab_2": habilidades[1],"hab_3": habilidades[2],"id": id}
        data.append(fila)

df_habilidades = pd.DataFrame(data)

df_habilidades = df_habilidades[["hab_1","hab_2","hab_3","id"]]

df_habilidades

                 hab_1        hab_2      hab_3      id
0             overgrow  chlorophyll        NaN     1.0
1             overgrow  chlorophyll        NaN     2.0
2            shed-skin          NaN        NaN    11.0
3           soundproof       static  aftermath   101.0
4      tablets-of-ruin          NaN        NaN  1001.0
...                ...          ...        ...     ...
1024  thermal-exchange     ice-body        NaN   996.0
1025  thermal-exchange     ice-body        NaN   997.0
1026  thermal-exchange     ice-body        NaN   998.0
1027           rattled          NaN        NaN   999.0
1028      good-as-gold          NaN        NaN  1000.0

[1029 rows x 4 columns]

In [35]:
df_stats

         hp  attack  defense  special-attack  special-defense  speed      id
0      45.0    49.0     49.0            65.0             65.0   45.0     1.0
1      60.0    62.0     63.0            80.0             80.0   60.0     2.0
2      50.0    20.0     55.0            25.0             25.0   30.0    11.0
3      60.0    50.0     70.0            80.0             80.0  150.0   101.0
4      85.0    85.0    100.0            95.0            135.0   70.0  1001.0
...     ...     ...      ...             ...              ...    ...     ...
1024   65.0    75.0     45.0            35.0             45.0   55.0   996.0
1025   90.0    95.0     66.0            45.0             65.0   62.0   997.0
1026  115.0   145.0     92.0            75.0             86.0   87.0   998.0
1027   45.0    30.0     70.0            75.0             70.0   10.0   999.0
1028   87.0    60.0     95.0           133.0             91.0   84.0  1000.0

[1029 rows x 7 columns]

In [36]:
df_types

         type1   type2      id
0        grass  poison     1.0
1        grass  poison     2.0
2          bug    None    11.0
3     electric    None   101.0
4         dark   grass  1001.0
...        ...     ...     ...
1024    dragon     ice   996.0
1025    dragon     ice   997.0
1026    dragon     ice   998.0
1027     ghost    None   999.0
1028     steel   ghost  1000.0

[1029 rows x 3 columns]

In [37]:
df_total = pd.merge(df_types,df_stats, on="id")
df_total = pd.merge(df_total,df_habilidades, on="id")

columnas = ["height","id","name","weight","ranking","popularity","base_experience"]

df = df[columnas]

df_total = pd.merge(df_total, df, on="id")

df_total

,type1,type2,id,hp,attack,defense,special-attack,special-defense,speed,hab_1,hab_2,hab_3,height,name,weight,ranking,popularity,base_experience
0,grass,poison,1.0,45.0,49.0,49.0,65.0,65.0,45.0,overgrow,chlorophyll,NaN,7.0,bulbasaur,69.0,28.0,72.8%,64.0
1,grass,poison,2.0,60.0,62.0,63.0,80.0,80.0,60.0,overgrow,chlorophyll,NaN,10.0,ivysaur,130.0,56.0,70.7%,142.0
2,bug,None,11.0,50.0,20.0,55.0,25.0,25.0,30.0,shed-skin,NaN,NaN,7.0,metapod,99.0,909.0,36%,72.0
3,electric,None,101.0,60.0,50.0,70.0,80.0,80.0,150.0,soundproof,static,aftermath,12.0,electrode,666.0,737.0,42.5%,172.0
4,dark,grass,1001.0,85.0,85.0,100.0,95.0,135.0,70.0,tablets-of-ruin,NaN,NaN,15.0,wo-chien,742.0,669.0,44.6%,285.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1066,dragon,ice,996.0,65.0,75.0,45.0,35.0,45.0,55.0,thermal-exchange,ice-body,NaN,5.0,frigibax,170.0,1016.0,25.5%,64.0
1067,dragon,ice,997.0,90.0,95.0,66.0,45.0,65.0,62.0,thermal-exchange,ice-body,NaN,8.0,arctibax,300.0,935.0,34.7%,148.0
1068,dragon,ice,998.0,115.0,145.0,92.0,75.0,86.0,87.0,thermal-exchange,ice-body,NaN,21.0,baxcalibur,2100.0,827.0,39.5%,300.0
1069,ghost,None,999.0,45.0,30.0,70.0,75.0,70.0,10.0,rattled,NaN,NaN,3.0,gimmighoul,50.0,726.0,42.8%,60.0
1070,steel,ghost,1000.0,87.0,60.0,95.0,133.0,91.0,84.0,good-as-gold,NaN,NaN,12.0,gholdengo,300.0,815.0,39.9%,275.0

In [38]:
df_total.duplicated().sum()

df_total = df_total.drop_duplicates()

In [39]:
df_total.columns

Index(['type1', 'type2', 'id', 'hp', 'attack', 'defense', 'special-attack',
       'special-defense', 'speed', 'hab_1', 'hab_2', 'hab_3', 'height', 'name',
       'weight', 'ranking', 'popularity', 'base_experience'],
      dtype='object')

In [40]:
df_total.to_csv("Pokemons.csv", encoding="utf-8")