# <img style="float: left; padding-right: 20px; width: 200px" src="https://raw.githubusercontent.com/raxlab/imt2200-data/main/media/logo.jpg">  IMT 2200 - Introducción a Ciencia de Datos
**Pontificia Universidad Católica de Chile**<br>
**Instituto de Ingeniería Matemática y Computacional**<br>
**Semestre 2025-S2**<br>
**Profesor:** Rodrigo A. Carrasco <br>

# <h1><center>Interrogación 1</center></h1>

## Instrucciones

* Esta parte de la Interrogación debe ser desarrollada completamente en lenguaje de programación Python en este Notebook de Jupyter.

* El desarrollo del Notebook debe ser claro y ordenado, incluyendo anotaciones (markdown) y comentarios que permitan seguir fácilmente el código y los pasos implementados, y siguiendo buenas prácticas de programación. <br>
* La entrega de la interrogación se realizará a través de Canvas en la actividad `I1 Desarrollo`.
* Esta Interrogación debe desarrollarse de manera totalmente *individual*, de acuerdo a lo establecido en la sección de Integridad Académica en el programa del curso.
* Está **estrictamente prohibido comunicarse con sus compañeros de curso, terceras personas o agentes de IA** durante el desarrollo de esta interrogación.
* Puede consultar los apuntes del curso de todo tipo.
* Habrá sólo dos instancias para hacer preguntas, una al inicio de la prueba y otra a los 30 minutos de avance.<br>


* Ud. dispone de 1 hora para desarrollar esta interrogación.
* Recuerde **guardar frecuentemente sus avances** para evitar pérdidas de trabajo o problemas de envío.<br>

*** 
## Parte 2: Trabajo de Desarrollo (60 min)

Esta parte de la Interrogación es un trabajo práctico con datos. En esta parte, cada pregunta debe ser respondida desarrollando un código por usted que le permita entregar una respuesta.

## 1. Extracción de datos de la red (6 pts.)

En esta sección, deberá escribir un código que le permita hacer una solicitud a una URL para obtener un archivo JSON.

Suponga que usted encuentra el siguiente endpoint en la documentación de una API:

```
URL = "www.example-api-url.com/LAT={latitude},LON={longitude},DATE={date (DD-MM-YYYY)}"
```

Complete la función `request_fnc` de modo que:
* Reciba como input (argumentos) los parámetros del endpoint y un nombre de archivo.
* Haga una solicitud a la URL.
* Guarde como JSON el contenido de la respuesta con el nombre del archivo dado.


**Solo escriba el código de la función sin llamarla, ya que está utilizando un URL de ejemplo.**

In [125]:
# Respuesta

def request_fnc(lat, lon, date, filename):
    # Escriba su código AQUI

_IncompleteInputError: incomplete input (329945953.py, line 4)

## 2. Lectura y creación de un DataFrame (6 pts.)

En la siguientes celdas (puede agregar celdas si lo necesita) escriba un código que lea el archivo `all_pokemon.json` que debió bajar a su computador antes de la prueba y lo deje en un DataFrame de pandas.

Cargue e inspeccione los índices del archivo. Luego, genere un único DataFrame que contenga las siguientes columnas:
```
["id", "name", "base_experience", "height", "weight", "is_default", "type1", "type2",
"hp","attack","defense","special-attack","special-defense","speed", "ranking", "popularity"]
```

Cuando corresponda, use métodos de aplanamiento (`json_normalize`). Puede crear múltiples DataFrames que le sean de utilidad en el proceso, pero debe obtener finalmente un solo DataFrame unificado con las columnas indicadas.

In [ ]:
import pandas as pd
from random import randint

In [ ]:
lista = ["id", "name", "base_experience", "height", "weight", "is_default", "type1", "type2",
"hp","attack","defense","special-attack","special-defense","speed", "ranking", "popularity"]

lista

['id',
 'name',
 'base_experience',
 'height',
 'weight',
 'is_default',
 'type1',
 'type2',
 'hp',
 'attack',
 'defense',
 'special-attack',
 'special-defense',
 'speed',
 'ranking',
 'popularity']

In [ ]:
# Respuesta
with open("../all_pokemon.json", encoding="utf-8") as df:
    df = pd.read_json(df)
print(f"Total de colunas: {len(df.columns)}\nLongitud total del dataframe: {len(df)}")
df.columns

Total de colunas: 22
Longitud total del dataframe: 1029

Index(['abilities', 'base_experience', 'cries', 'forms', 'game_indices',
       'height', 'held_items', 'id', 'is_default', 'location_area_encounters',
       'moves', 'name', 'order', 'past_abilities', 'past_types', 'species',
       'sprites', 'stats', 'types', 'weight', 'ranking', 'popularity'],
      dtype='object')

In [ ]:
col_agregar = []
for columna in lista:
    if columna not in l_df_columnas:
        col_agregar.append(columna)
print("Columnas por agregar:")
print(col_agregar)

Columnas por agregar:
['type1', 'type2', 'hp', 'attack', 'defense', 'special-attack', 'special-defense', 'speed']

In [ ]:
#Como las columnas por agregar provienen de stats y types, las normalizamos
df_stats = pd.json_normalize(df["stats"])
df_stats["id"] = df["id"]

df_types = pd.json_normalize(df["types"])
df_types['id'] = df['id']


#df['stats'] = df_stats.copy()
#df['types'] = df_types.copy()


print(len(df_types), len(df_stats))
print(len(df['stats']))

df_total = pd.merge(df_types,df_stats, on="id")
df_total['species'] = df['species'].copy()
df_total['name'] = df['name'].copy()
df_total['base_experience'] = df['base_experience'].copy()
df_total['height'] = df['height'].copy()
df_total['weight'] = df['weight'].copy()
df_total['is_default'] = df['is_default'].copy()
df_total['ranking'] = df['ranking'].copy()
df_total['popularity'] = df['popularity'].copy()
display(df_total.head())

print(f"Numero de columnas: {len(df_total.columns)}")

1029 1029
1029

,type1,type2,id,hp,attack,defense,special-attack,special-defense,speed,species,name,base_experience,height,weight,is_default,ranking,popularity
0,grass,poison,1.0,45.0,49.0,49.0,65.0,65.0,45.0,"{'name': 'bulbasaur', 'url': 'https://pokeapi....",bulbasaur,64.0,7.0,69.0,1.0,28.0,72.8%
1,grass,poison,2.0,60.0,62.0,63.0,80.0,80.0,60.0,"{'name': 'ivysaur', 'url': 'https://pokeapi.co...",ivysaur,142.0,10.0,130.0,1.0,56.0,70.7%
2,bug,None,11.0,50.0,20.0,55.0,25.0,25.0,30.0,"{'name': 'metapod', 'url': 'https://pokeapi.co...",metapod,72.0,7.0,99.0,1.0,909.0,36%
3,electric,None,101.0,60.0,50.0,70.0,80.0,80.0,150.0,"{'name': 'electrode', 'url': 'https://pokeapi....",electrode,172.0,12.0,666.0,1.0,737.0,42.5%
4,dark,grass,1001.0,85.0,85.0,100.0,95.0,135.0,70.0,"{'name': 'wo-chien', 'url': 'https://pokeapi.c...",wo-chien,285.0,15.0,742.0,1.0,669.0,44.6%

Numero de columnas: 17

#### Consideracion columna ID
- Se agrega por concatenar df_type y df_stats, gracias por la comprension.

## 3. Inspección de los datos

En esta sección, inspeccione el DataFrame generado y responda con texto y/o código según corresponda.

#### 3.1 Imprima una muestra de 5 filas al azar de su dataset (3 pts.)

In [ ]:
# Respuesta MODIFICAR

df_total.head()

,type1,type2,id,hp,attack,defense,special-attack,special-defense,speed,species,name,base_experience,height,weight,is_default,ranking,popularity
0,grass,poison,1.0,45.0,49.0,49.0,65.0,65.0,45.0,"{'name': 'bulbasaur', 'url': 'https://pokeapi....",bulbasaur,64.0,7.0,69.0,1.0,28.0,72.8%
1,grass,poison,2.0,60.0,62.0,63.0,80.0,80.0,60.0,"{'name': 'ivysaur', 'url': 'https://pokeapi.co...",ivysaur,142.0,10.0,130.0,1.0,56.0,70.7%
2,bug,None,11.0,50.0,20.0,55.0,25.0,25.0,30.0,"{'name': 'metapod', 'url': 'https://pokeapi.co...",metapod,72.0,7.0,99.0,1.0,909.0,36%
3,electric,None,101.0,60.0,50.0,70.0,80.0,80.0,150.0,"{'name': 'electrode', 'url': 'https://pokeapi....",electrode,172.0,12.0,666.0,1.0,737.0,42.5%
4,dark,grass,1001.0,85.0,85.0,100.0,95.0,135.0,70.0,"{'name': 'wo-chien', 'url': 'https://pokeapi.c...",wo-chien,285.0,15.0,742.0,1.0,669.0,44.6%

#### 3.2 Imprima un resumen de los estadísticos principales (cantidad, valor promedio, máximos y mínimos, etc) para todas las columnas numérticas de su dataset (3 pts.)

In [ ]:
# Respuesta
df_total.describe() #muestra solo datos de las numericas

,id,hp,attack,defense,special-attack,special-defense,speed,base_experience,height,weight,is_default,ranking
count,1034.000000,1034.000000,1034.000000,1034.000000,1034.000000,1034.000000,1034.000000,1028.000000,1028.000000,1028.000000,1028.0,1028.000000
mean,512.939072,70.191489,77.412959,72.470986,69.891683,70.117021,67.065764,150.904669,12.105058,668.751946,1.0,513.085603
std,294.803246,26.719258,29.794986,29.244565,29.623319,26.624651,28.702728,78.845397,12.466456,1211.192251,0.0,296.069287
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,36.000000,1.000000,1.000000,1.0,1.000000
25%,259.250000,50.000000,55.000000,50.000000,47.000000,50.000000,45.000000,66.000000,5.000000,85.000000,1.0,257.750000
50%,514.500000,67.500000,75.000000,70.000000,65.000000,66.000000,65.000000,158.000000,10.000000,280.000000,1.0,512.500000
75%,766.750000,85.000000,100.000000,90.000000,90.000000,85.000000,87.750000,184.000000,15.000000,700.000000,1.0,769.250000
max,1025.000000,255.000000,181.000000,230.000000,173.000000,230.000000,200.000000,608.000000,200.000000,9999.000000,1.0,1025.000000

#### 3.3 Imprima todos los valores de `type1` y `type2` que existen en su dataset. ¿Cuántos son? (3 pts.)

In [ ]:
# Respuesta
for i, elem in enumerate(df_total['type1']):
    print(f"({i}) - Type1: {elem}, Type2: {df_total['type2'][i]}")
print(f"\nNumero total de tipos: {len(df_total['type1'])}")

(0) - Type1: grass, Type2: poison
(1) - Type1: grass, Type2: poison
(2) - Type1: bug, Type2: None
(3) - Type1: electric, Type2: None
(4) - Type1: dark, Type2: grass
(5) - Type1: dark, Type2: ice
(6) - Type1: dark, Type2: ground
(7) - Type1: dark, Type2: fire
(8) - Type1: dragon, Type2: dark
(9) - Type1: fairy, Type2: fighting
(10) - Type1: fighting, Type2: dragon
(11) - Type1: electric, Type2: dragon
(12) - Type1: water, Type2: dragon
(13) - Type1: grass, Type2: psychic
(14) - Type1: grass, Type2: psychic
(15) - Type1: grass, Type2: dragon
(16) - Type1: grass, Type2: ghost
(17) - Type1: grass, Type2: ghost
(18) - Type1: poison, Type2: fighting
(19) - Type1: poison, Type2: psychic
(20) - Type1: poison, Type2: fairy
(21) - Type1: grass, Type2: None
(22) - Type1: steel, Type2: dragon
(23) - Type1: grass, Type2: dragon
(24) - Type1: fire, Type2: dragon
(25) - Type1: grass, Type2: psychic
(26) - Type1: electric, Type2: dragon
(27) - Type1: rock, Type2: psychic
(28) - Type1: steel, Type2: psychic
(29) - Type1: normal, Type2: None
(30) - Type1: poison, Type2: ghost
(31) - Type1: ground, Type2: None
(32) - Type1: ground, Type2: None
(33) - Type1: fighting, Type2: None
(34) - Type1: fighting, Type2: None
(35) - Type1: normal, Type2: None
(36) - Type1: poison, Type2: None
(37) - Type1: poison, Type2: None
(38) - Type1: bug, Type2: flying
(39) - Type1: ground, Type2: rock
(40) - Type1: ground, Type2: rock
(41) - Type1: normal, Type2: None
(42) - Type1: grass, Type2: None
(43) - Type1: normal, Type2: None
(44) - Type1: water, Type2: None
(45) - Type1: water, Type2: None
(46) - Type1: water, Type2: None
(47) - Type1: water, Type2: None
(48) - Type1: water, Type2: None
(49) - Type1: bug, Type2: poison
(50) - Type1: water, Type2: psychic
(51) - Type1: psychic, Type2: fairy
(52) - Type1: bug, Type2: flying
(53) - Type1: ice, Type2: psychic
(54) - Type1: electric, Type2: None
(55) - Type1: fire, Type2: None
(56) - Type1: bug, Type2: None
(57) - Type1: normal, Type2: None
(58) - Type1: water, Type2: None
(59) - Type1: water, Type2: flying
(60) - Type1: bug, Type2: poison
(61) - Type1: water, Type2: ice
(62) - Type1: normal, Type2: None
(63) - Type1: normal, Type2: None
(64) - Type1: water, Type2: None
(65) - Type1: electric, Type2: None
(66) - Type1: fire, Type2: None
(67) - Type1: normal, Type2: None
(68) - Type1: rock, Type2: water
(69) - Type1: rock, Type2: water
(70) - Type1: rock, Type2: water
(71) - Type1: bug, Type2: poison
(72) - Type1: rock, Type2: water
(73) - Type1: rock, Type2: flying
(74) - Type1: normal, Type2: None
(75) - Type1: ice, Type2: flying
(76) - Type1: electric, Type2: flying
(77) - Type1: fire, Type2: flying
(78) - Type1: dragon, Type2: None
(79) - Type1: dragon, Type2: None
(80) - Type1: dragon, Type2: flying
(81) - Type1: psychic, Type2: None
(82) - Type1: normal, Type2: flying
(83) - Type1: psychic, Type2: None
(84) - Type1: grass, Type2: None
(85) - Type1: grass, Type2: None
(86) - Type1: grass, Type2: None
(87) - Type1: fire, Type2: None
(88) - Type1: fire, Type2: None
(89) - Type1: fire, Type2: None
(90) - Type1: water, Type2: None
(91) - Type1: water, Type2: None
(92) - Type1: water, Type2: None
(93) - Type1: normal, Type2: flying
(94) - Type1: normal, Type2: None
(95) - Type1: normal, Type2: None
(96) - Type1: normal, Type2: flying
(97) - Type1: normal, Type2: flying
(98) - Type1: bug, Type2: flying
(99) - Type1: bug, Type2: flying
(100) - Type1: bug, Type2: poison
(101) - Type1: bug, Type2: poison
(102) - Type1: poison, Type2: flying
(103) - Type1: water, Type2: electric
(104) - Type1: normal, Type2: flying
(105) - Type1: water, Type2: electric
(106) - Type1: electric, Type2: None
(107) - Type1: fairy, Type2: None
(108) - Type1: normal, Type2: fairy
(109) - Type1: fairy, Type2: None
(110) - Type1: fairy, Type2: flying
(111) - Type1: psychic, Type2: flying
(112) - Type1: psychic, Type2: flying
(113) - Type1: electric, Type2: None
(114) - Type1: electric, Type2: None
(115) - Type1: normal, Type2: None
(116) - Type1: electric, Type2: None
(117) - Type1: grass, Type2: None
(118) - Type1: water, Type2: fairy
(119) - Type1: water, Type2: fairy
(120) - Type1: rock, Type2: None
(121) - Type1: water, Type2: None
(122) - Type1: grass, Type2: flying
(123) - Type1: grass, Type2: flying
(124) - Type1: grass, Type2: flying
(125) - Type1: normal, Type2: None
(126) - Type1: normal, Type2: None
(127) - Type1: grass, Type2: None
(128) - Type1: grass, Type2: None
(129) - Type1: bug, Type2: flying
(130) - Type1: water, Type2: ground
(131) - Type1: water, Type2: ground
(132) - Type1: psychic, Type2: None
(133) - Type1: dark, Type2: None
(134) - Type1: dark, Type2: flying
(135) - Type1: water, Type2: psychic
(136) - Type1: ghost, Type2: None
(137) - Type1: grass, Type2: poison
(138) - Type1: normal, Type2: flying
(139) - Type1: psychic, Type2: None
(140) - Type1: psychic, Type2: None
(141) - Type1: normal, Type2: psychic
(142) - Type1: bug, Type2: None
(143) - Type1: bug, Type2: steel
(144) - Type1: normal, Type2: None
(145) - Type1: ground, Type2: flying
(146) - Type1: steel, Type2: ground
(147) - Type1: fairy, Type2: None
(148) - Type1: fairy, Type2: None
(149) - Type1: normal, Type2: flying
(150) - Type1: water, Type2: poison
(151) - Type1: bug, Type2: steel
(152) - Type1: bug, Type2: rock
(153) - Type1: bug, Type2: fighting
(154) - Type1: dark, Type2: ice
(155) - Type1: normal, Type2: None
(156) - Type1: normal, Type2: None
(157) - Type1: fire, Type2: None
(158) - Type1: fire, Type2: rock
(159) - Type1: ice, Type2: ground
(160) - Type1: poison, Type2: None
(161) - Type1: ice, Type2: ground
(162) - Type1: water, Type2: rock
(163) - Type1: water, Type2: None
(164) - Type1: water, Type2: None
(165) - Type1: ice, Type2: flying
(166) - Type1: water, Type2: flying
(167) - Type1: steel, Type2: flying
(168) - Type1: dark, Type2: fire
(169) - Type1: dark, Type2: fire
(170) - Type1: water, Type2: dragon
(171) - Type1: poison, Type2: None
(172) - Type1: ground, Type2: None
(173) - Type1: ground, Type2: None
(174) - Type1: normal, Type2: None
(175) - Type1: normal, Type2: None
(176) - Type1: normal, Type2: None
(177) - Type1: fighting, Type2: None
(178) - Type1: fighting, Type2: None
(179) - Type1: ice, Type2: psychic
(180) - Type1: electric, Type2: None
(181) - Type1: fire, Type2: None
(182) - Type1: electric, Type2: None
(183) - Type1: normal, Type2: None
(184) - Type1: normal, Type2: None
(185) - Type1: electric, Type2: None
(186) - Type1: fire, Type2: None
(187) - Type1: water, Type2: None
(188) - Type1: rock, Type2: ground
(189) - Type1: rock, Type2: ground
(190) - Type1: rock, Type2: dark
(191) - Type1: psychic, Type2: flying
(192) - Type1: fire, Type2: flying
(193) - Type1: electric, Type2: None
(194) - Type1: psychic, Type2: grass
(195) - Type1: grass, Type2: None
(196) - Type1: grass, Type2: None
(197) - Type1: grass, Type2: None
(198) - Type1: fire, Type2: None
(199) - Type1: fire, Type2: fighting
(200) - Type1: fire, Type2: fighting
(201) - Type1: water, Type2: None
(202) - Type1: water, Type2: ground
(203) - Type1: water, Type2: ground
(204) - Type1: ground, Type2: None
(205) - Type1: dark, Type2: None
(206) - Type1: dark, Type2: None
(207) - Type1: normal, Type2: None
(208) - Type1: normal, Type2: None
(209) - Type1: bug, Type2: None
(210) - Type1: bug, Type2: None
(211) - Type1: bug, Type2: flying
(212) - Type1: bug, Type2: None
(213) - Type1: bug, Type2: poison
(214) - Type1: water, Type2: grass
(215) - Type1: ground, Type2: None
(216) - Type1: water, Type2: grass
(217) - Type1: water, Type2: grass
(218) - Type1: grass, Type2: None
(219) - Type1: grass, Type2: dark
(220) - Type1: grass, Type2: dark
(221) - Type1: normal, Type2: flying
(222) - Type1: normal, Type2: flying
(223) - Type1: water, Type2: flying
(224) - Type1: water, Type2: flying
(225) - Type1: psychic, Type2: fairy
(226) - Type1: poison, Type2: None
(227) - Type1: psychic, Type2: fairy
(228) - Type1: psychic, Type2: fairy
(229) - Type1: bug, Type2: water
(230) - Type1: bug, Type2: flying
(231) - Type1: grass, Type2: None
(232) - Type1: grass, Type2: fighting
(233) - Type1: normal, Type2: None
(234) - Type1: normal, Type2: None
(235) - Type1: normal, Type2: None
(236) - Type1: bug, Type2: ground
(237) - Type1: poison, Type2: None
(238) - Type1: bug, Type2: flying
(239) - Type1: bug, Type2: ghost
(240) - Type1: normal, Type2: None
(241) - Type1: normal, Type2: None
(242) - Type1: normal, Type2: None
(243) - Type1: fighting, Type2: None
(244) - Type1: fighting, Type2: None
(245) - Type1: normal, Type2: fairy
(246) - Type1: rock, Type2: None
(247) - Type1: normal, Type2: None
(248) - Type1: fire, Type2: None
(249) - Type1: poison, Type2: ground
(250) - Type1: normal, Type2: None
(251) - Type1: dark, Type2: ghost
(252) - Type1: steel, Type2: fairy
(253) - Type1: steel, Type2: rock
(254) - Type1: steel, Type2: rock
(255) - Type1: steel, Type2: rock
(256) - Type1: fighting, Type2: psychic
(257) - Type1: fighting, Type2: psychic
(258) - Type1: electric, Type2: None
(259) - Type1: electric, Type2: None
(260) - Type1: poison, Type2: None
(261) - Type1: electric, Type2: None
(262) - Type1: electric, Type2: None
(263) - Type1: bug, Type2: None
(264) - Type1: bug, Type2: None
(265) - Type1: grass, Type2: poison
(266) - Type1: poison, Type2: None
(267) - Type1: poison, Type2: None
(268) - Type1: water, Type2: dark
(269) - Type1: water, Type2: dark
(270) - Type1: water, Type2: None
(271) - Type1: poison, Type2: None
(272) - Type1: water, Type2: None
(273) - Type1: fire, Type2: ground
(274) - Type1: fire, Type2: ground
(275) - Type1: fire, Type2: None
(276) - Type1: psychic, Type2: None
(277) - Type1: psychic, Type2: None
(278) - Type1: normal, Type2: None
(279) - Type1: ground, Type2: None
(280) - Type1: ground, Type2: dragon
(281) - Type1: ground, Type2: dragon
(282) - Type1: poison, Type2: ground
(283) - Type1: grass, Type2: None
(284) - Type1: grass, Type2: dark
(285) - Type1: normal, Type2: flying
(286) - Type1: dragon, Type2: flying
(287) - Type1: normal, Type2: None
(288) - Type1: poison, Type2: None
(289) - Type1: rock, Type2: psychic
(290) - Type1: rock, Type2: psychic
(291) - Type1: water, Type2: ground
(292) - Type1: water, Type2: ground
(293) - Type1: fairy, Type2: None
(294) - Type1: water, Type2: None
(295) - Type1: water, Type2: dark
(296) - Type1: ground, Type2: psychic
(297) - Type1: ground, Type2: psychic
(298) - Type1: rock, Type2: grass
(299) - Type1: rock, Type2: grass
(300) - Type1: rock, Type2: bug
(301) - Type1: rock, Type2: bug
(302) - Type1: water, Type2: None
(303) - Type1: water, Type2: None
(304) - Type1: fairy, Type2: None
(305) - Type1: normal, Type2: None
(306) - Type1: normal, Type2: None
(307) - Type1: ghost, Type2: None
(308) - Type1: ghost, Type2: None
(309) - Type1: ghost, Type2: None
(310) - Type1: ghost, Type2: None
(311) - Type1: grass, Type2: flying
(312) - Type1: psychic, Type2: None
(313) - Type1: dark, Type2: None
(314) - Type1: psychic, Type2: None
(315) - Type1: fire, Type2: None
(316) - Type1: ice, Type2: None
(317) - Type1: ice, Type2: None
(318) - Type1: ice, Type2: water
(319) - Type1: ice, Type2: water
(320) - Type1: ice, Type2: water
(321) - Type1: water, Type2: None
(322) - Type1: water, Type2: None
(323) - Type1: water, Type2: None
(324) - Type1: water, Type2: rock
(325) - Type1: water, Type2: None
(326) - Type1: fire, Type2: None
(327) - Type1: dragon, Type2: None
(328) - Type1: dragon, Type2: None
(329) - Type1: dragon, Type2: flying
(330) - Type1: steel, Type2: psychic
(331) - Type1: steel, Type2: psychic
(332) - Type1: steel, Type2: psychic
(333) - Type1: rock, Type2: None
(334) - Type1: ice, Type2: None
(335) - Type1: steel, Type2: None
(336) - Type1: dragon, Type2: psychic
(337) - Type1: normal, Type2: fairy
(338) - Type1: dragon, Type2: psychic
(339) - Type1: water, Type2: None
(340) - Type1: ground, Type2: None
(341) - Type1: dragon, Type2: flying
(342) - Type1: steel, Type2: psychic
(343) - Type1: psychic, Type2: None
(344) - Type1: grass, Type2: None
(345) - Type1: grass, Type2: None
(346) - Type1: grass, Type2: ground
(347) - Type1: fire, Type2: None
(348) - Type1: normal, Type2: fairy
(349) - Type1: fire, Type2: fighting
(350) - Type1: fire, Type2: fighting
(351) - Type1: water, Type2: None
(352) - Type1: water, Type2: None
(353) - Type1: water, Type2: steel
(354) - Type1: normal, Type2: flying
(355) - Type1: normal, Type2: flying
(356) - Type1: normal, Type2: flying
(357) - Type1: normal, Type2: None
(358) - Type1: normal, Type2: water
(359) - Type1: fire, Type2: None
(360) - Type1: poison, Type2: flying
(361) - Type1: bug, Type2: None
(362) - Type1: bug, Type2: None
(363) - Type1: electric, Type2: None
(364) - Type1: electric, Type2: None
(365) - Type1: electric, Type2: None
(366) - Type1: grass, Type2: poison
(367) - Type1: grass, Type2: poison
(368) - Type1: rock, Type2: None
(369) - Type1: rock, Type2: None
(370) - Type1: rock, Type2: steel
(371) - Type1: poison, Type2: flying
(372) - Type1: rock, Type2: steel
(373) - Type1: bug, Type2: None
(374) - Type1: bug, Type2: grass
(375) - Type1: bug, Type2: flying
(376) - Type1: bug, Type2: flying
(377) - Type1: bug, Type2: flying
(378) - Type1: electric, Type2: None
(379) - Type1: water, Type2: None
(380) - Type1: water, Type2: None
(381) - Type1: water, Type2: None
(382) - Type1: water, Type2: None
(383) - Type1: water, Type2: None
(384) - Type1: grass, Type2: None
(385) - Type1: grass, Type2: poison
(386) - Type1: grass, Type2: None
(387) - Type1: water, Type2: None
(388) - Type1: water, Type2: ground
(389) - Type1: normal, Type2: None
(390) - Type1: ghost, Type2: flying
(391) - Type1: ghost, Type2: flying
(392) - Type1: normal, Type2: None
(393) - Type1: normal, Type2: None
(394) - Type1: ghost, Type2: None
(395) - Type1: dark, Type2: flying
(396) - Type1: grass, Type2: poison
(397) - Type1: normal, Type2: None
(398) - Type1: normal, Type2: None
(399) - Type1: psychic, Type2: None
(400) - Type1: poison, Type2: dark
(401) - Type1: poison, Type2: dark
(402) - Type1: steel, Type2: psychic
(403) - Type1: steel, Type2: psychic
(404) - Type1: rock, Type2: None
(405) - Type1: psychic, Type2: fairy
(406) - Type1: normal, Type2: None
(407) - Type1: grass, Type2: poison
(408) - Type1: normal, Type2: flying
(409) - Type1: ghost, Type2: dark
(410) - Type1: dragon, Type2: ground
(411) - Type1: dragon, Type2: ground
(412) - Type1: dragon, Type2: ground
(413) - Type1: normal, Type2: None
(414) - Type1: fighting, Type2: None
(415) - Type1: fighting, Type2: steel
(416) - Type1: ground, Type2: None
(417) - Type1: ground, Type2: None
(418) - Type1: bug, Type2: grass
(419) - Type1: poison, Type2: bug
(420) - Type1: poison, Type2: dark
(421) - Type1: poison, Type2: fighting
(422) - Type1: poison, Type2: fighting
(423) - Type1: grass, Type2: None
(424) - Type1: water, Type2: None
(425) - Type1: water, Type2: None
(426) - Type1: water, Type2: flying
(427) - Type1: grass, Type2: ice
(428) - Type1: grass, Type2: ice
(429) - Type1: bug, Type2: grass
(430) - Type1: dark, Type2: ice
(431) - Type1: electric, Type2: steel
(432) - Type1: normal, Type2: None
(433) - Type1: ground, Type2: rock
(434) - Type1: grass, Type2: None
(435) - Type1: electric, Type2: None
(436) - Type1: fire, Type2: None
(437) - Type1: fairy, Type2: flying
(438) - Type1: bug, Type2: flying
(439) - Type1: grass, Type2: None
(440) - Type1: bug, Type2: poison
(441) - Type1: ice, Type2: None
(442) - Type1: ground, Type2: flying
(443) - Type1: ice, Type2: ground
(444) - Type1: normal, Type2: None
(445) - Type1: psychic, Type2: fighting
(446) - Type1: rock, Type2: steel
(447) - Type1: ghost, Type2: None
(448) - Type1: ice, Type2: ghost
(449) - Type1: electric, Type2: ghost
(450) - Type1: psychic, Type2: None
(451) - Type1: bug, Type2: poison
(452) - Type1: psychic, Type2: None
(453) - Type1: psychic, Type2: None
(454) - Type1: steel, Type2: dragon
(455) - Type1: water, Type2: dragon
(456) - Type1: fire, Type2: steel
(457) - Type1: normal, Type2: None
(458) - Type1: ghost, Type2: dragon
(459) - Type1: psychic, Type2: None
(460) - Type1: water, Type2: None
(461) - Type1: water, Type2: None
(462) - Type1: ground, Type2: None
(463) - Type1: dark, Type2: None
(464) - Type1: grass, Type2: None
(465) - Type1: normal, Type2: None
(466) - Type1: psychic, Type2: fire
(467) - Type1: grass, Type2: None
(468) - Type1: grass, Type2: None
(469) - Type1: grass, Type2: None
(470) - Type1: fire, Type2: None
(471) - Type1: fire, Type2: fighting
(472) - Type1: fire, Type2: fighting
(473) - Type1: fire, Type2: flying
(474) - Type1: ground, Type2: None
(475) - Type1: water, Type2: None
(476) - Type1: water, Type2: None
(477) - Type1: water, Type2: None
(478) - Type1: normal, Type2: None
(479) - Type1: normal, Type2: None
(480) - Type1: normal, Type2: None
(481) - Type1: normal, Type2: None
(482) - Type1: normal, Type2: None
(483) - Type1: dark, Type2: None
(484) - Type1: dark, Type2: None
(485) - Type1: normal, Type2: None
(486) - Type1: grass, Type2: None
(487) - Type1: grass, Type2: None
(488) - Type1: fire, Type2: None
(489) - Type1: fire, Type2: None
(490) - Type1: water, Type2: None
(491) - Type1: water, Type2: None
(492) - Type1: psychic, Type2: None
(493) - Type1: psychic, Type2: None
(494) - Type1: normal, Type2: flying
(495) - Type1: normal, Type2: flying
(496) - Type1: normal, Type2: None
(497) - Type1: normal, Type2: flying
(498) - Type1: electric, Type2: None
(499) - Type1: electric, Type2: None
(500) - Type1: rock, Type2: None
(501) - Type1: rock, Type2: None
(502) - Type1: rock, Type2: None
(503) - Type1: psychic, Type2: flying
(504) - Type1: psychic, Type2: flying
(505) - Type1: ground, Type2: None
(506) - Type1: ground, Type2: steel
(507) - Type1: water, Type2: None
(508) - Type1: normal, Type2: None
(509) - Type1: fighting, Type2: None
(510) - Type1: fighting, Type2: None
(511) - Type1: fighting, Type2: None
(512) - Type1: water, Type2: None
(513) - Type1: water, Type2: ground
(514) - Type1: water, Type2: ground
(515) - Type1: fighting, Type2: None
(516) - Type1: fighting, Type2: None
(517) - Type1: fighting, Type2: None
(518) - Type1: fighting, Type2: None
(519) - Type1: fighting, Type2: None
(520) - Type1: bug, Type2: grass
(521) - Type1: water, Type2: None
(522) - Type1: bug, Type2: grass
(523) - Type1: bug, Type2: grass
(524) - Type1: bug, Type2: poison
(525) - Type1: bug, Type2: poison
(526) - Type1: bug, Type2: poison
(527) - Type1: grass, Type2: fairy
(528) - Type1: grass, Type2: fairy
(529) - Type1: grass, Type2: None
(530) - Type1: grass, Type2: None
(531) - Type1: water, Type2: None
(532) - Type1: fighting, Type2: None
(533) - Type1: ground, Type2: dark
(534) - Type1: ground, Type2: dark
(535) - Type1: ground, Type2: dark
(536) - Type1: fire, Type2: None
(537) - Type1: fire, Type2: None
(538) - Type1: grass, Type2: None
(539) - Type1: bug, Type2: rock
(540) - Type1: bug, Type2: rock
(541) - Type1: dark, Type2: fighting
(542) - Type1: dark, Type2: fighting
(543) - Type1: fighting, Type2: None
(544) - Type1: psychic, Type2: flying
(545) - Type1: ghost, Type2: None
(546) - Type1: ghost, Type2: None
(547) - Type1: ghost, Type2: None
(548) - Type1: ghost, Type2: None
(549) - Type1: ghost, Type2: None
(550) - Type1: water, Type2: rock
(551) - Type1: water, Type2: rock
(552) - Type1: rock, Type2: flying
(553) - Type1: rock, Type2: flying
(554) - Type1: poison, Type2: None
(555) - Type1: poison, Type2: None
(556) - Type1: dark, Type2: None
(557) - Type1: fire, Type2: None
(558) - Type1: dark, Type2: None
(559) - Type1: normal, Type2: None
(560) - Type1: normal, Type2: None
(561) - Type1: psychic, Type2: None
(562) - Type1: psychic, Type2: None
(563) - Type1: psychic, Type2: None
(564) - Type1: psychic, Type2: None
(565) - Type1: psychic, Type2: None
(566) - Type1: psychic, Type2: None
(567) - Type1: water, Type2: flying
(568) - Type1: fire, Type2: None
(569) - Type1: water, Type2: flying
(570) - Type1: ice, Type2: None
(571) - Type1: ice, Type2: None
(572) - Type1: ice, Type2: None

#### 3.4 Muestre los tipos de cada columna de su DataFrame (3 pts.)

In [ ]:
# Respuesta
df_total.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1035 entries, 0 to 1034
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   type1            1034 non-null   object
 1   type2            526 non-null    object
 2   id               1034 non-null   float64
 3   hp               1034 non-null   float64
 4   attack           1034 non-null   float64
 5   defense          1034 non-null   float64
 6   special-attack   1034 non-null   float64
 7   special-defense  1034 non-null   float64
 8   speed            1034 non-null   float64
 9   species          1028 non-null   object
 10  name             1028 non-null   object
 11  base_experience  1028 non-null   float64
 12  height           1028 non-null   float64
 13  weight           1028 non-null   float64
 14  is_default       1028 non-null   float64
 15  ranking          1028 non-null   float64
 16  popularity       1028 non-null   object
dtypes: float64(12), object(5)
memory usage: 137.6+ KB

#### 3.5 ¿Están correctos los tipos asignados por Pandas? ¿Cree que algunos podrían ser modificados? Justifique su respuesta. (5 pts.)

- Considerando que `popularity` es un porcentaje, podria cambiar a tipo `float64`. Hay que considerar que contiene el str %, por eso está en tipo object. Sin ambargo, aplicando correcta limpieza, podría cambiarse el tip para poder hacer mayor análisis

Respuesta:

## 4. Limpieza del dataset

Para la siguiente sección, deberá crear un nuevo DataFrame **sin sobreescribir el anterior** llamado `clean_df`. Responda las preguntas con texto y/o código según corresponda.

In [ ]:
# Nuevo DF
clean_df = df_total.copy()

#### 4.1 ¿Existen filas con valores nulos en su DataFrame? Si es así, imprima cuáles filas contienen valores nulos. ¿Cuántas son? En caso contrario, escriba el código que le permite saber que no hay valores nulos. (4 pts.)

In [ ]:
# Respuesta

1035

#### 4.2 Según lo obtenido, elimine las filas que considere inválidas de `clean_df` y justifique porqué. Si no encontró ninguna, escriba el código que le permitiría eliminar filas nulas de `clean_df`. (4 pts.)

Respuesta:

In [ ]:
# Respuesta

#### 4.3 ¿Existen filas duplicadas en su DataFrame? Si es así, muestre cuáles son. Si no, escriba el código que le permite saberlo. (3 pts.)

In [ ]:
print(len(clean_df))

1035

In [ ]:
# Respuesta
print(f"La cantidad de valores únicos de pokemon_name es: {len(clean_df['name'].unique())}")

#Como hay pokemones repetidos, veremos cuale son:
print(clean_df['name'].value_counts()[clean_df['name'].value_counts() > 1])

La cantidad de valores únicos de pokemon_name es: 1027
name
yamask    2
buizel    2
throh     2
Name: count, dtype: int64

#### 4.4 Elimine las filas duplicadas de `clean_df`, dejando únicamente el primer registro. Si no hay ninguna, escriba el código que le permitiría eliminar filas duplicadas de `clean_df`. (4 pts.)

In [ ]:
# Respuesta, como existen 3 filas duplicadas, las eliminamos

#Los podríamos eliminar así, se duplicados de la columna pokemon_name
clean_df = clean_df.drop_duplicates(subset=['name'], keep='first') #subset=['name'],

#Concluimos
print("\nPor lo tanto:")
print(f"Los pokemones totales (sin filtrar) son: {len(df_total)}\nPero los totales filtrados (sin repeticiones) son: {len(clean_df)}. Notar que coinciden con los registros unicos.")

Por lo tanto:
Los pokemones totales (sin filtrar) son: 1035
Pero los totales filtrados (sin repeticiones) son: 1027. Notar que coinciden con los registros unicos.

#### 4.5 Acorde con lo que respondió en el item 3.5, aplique las transformaciones a los tipos a las columnas que consideró incorrectas. Imprima nuevamente los nuevos tipos de todas las columnas (5 pts.)

In [ ]:
# Respuesta

for i, elem in enumerate(clean_df['popularity']):
    porcentaje = elem[:-1]
    
    clean_df['popularity'][i] = float(porcentaje)
    if i == 0:
        print(porcentaje)
clean_df.tail()

TypeError: 'float' object is not subscriptable

#### 4.6 ¿Hay alguna columna que podría eliminar de su dataset? Justifique su respuesta. Si considera que existe alguna, escriba y ejecute un código que elimine esta columna de `clean_df`. En caso contrario, escriba un código que elimine una columna cualquiera, pero no lo ejecute (3 pts.)

In [ ]:
# Respuesta
clean_df.head()

,type1,type2,id,hp,attack,defense,special-attack,special-defense,speed,species,name,base_experience,height,weight,is_default,ranking,popularity
0,grass,poison,1.0,45.0,49.0,49.0,65.0,65.0,45.0,"{'name': 'bulbasaur', 'url': 'https://pokeapi....",bulbasaur,64.0,7.0,69.0,1.0,28.0,72.8%
1,grass,poison,2.0,60.0,62.0,63.0,80.0,80.0,60.0,"{'name': 'ivysaur', 'url': 'https://pokeapi.co...",ivysaur,142.0,10.0,130.0,1.0,56.0,70.7%
2,bug,None,11.0,50.0,20.0,55.0,25.0,25.0,30.0,"{'name': 'metapod', 'url': 'https://pokeapi.co...",metapod,72.0,7.0,99.0,1.0,909.0,36%
3,electric,None,101.0,60.0,50.0,70.0,80.0,80.0,150.0,"{'name': 'electrode', 'url': 'https://pokeapi....",electrode,172.0,12.0,666.0,1.0,737.0,42.5%
4,dark,grass,1001.0,85.0,85.0,100.0,95.0,135.0,70.0,"{'name': 'wo-chien', 'url': 'https://pokeapi.c...",wo-chien,285.0,15.0,742.0,1.0,669.0,44.6%

In [ ]:
clean_df['species'][0]

{'name': 'bulbasaur', 'url': 'https://pokeapi.co/api/v2/pokemon-species/1/'}

In [ ]:
#No aporta nda fundamental, se elimina
clean_df= clean_df.drop(columns='species')
clean_df.head()

,type1,type2,id,hp,attack,defense,special-attack,special-defense,speed,name,base_experience,height,weight,is_default,ranking,popularity
0,grass,poison,1.0,45.0,49.0,49.0,65.0,65.0,45.0,bulbasaur,64.0,7.0,69.0,1.0,28.0,72.8%
1,grass,poison,2.0,60.0,62.0,63.0,80.0,80.0,60.0,ivysaur,142.0,10.0,130.0,1.0,56.0,70.7%
2,bug,None,11.0,50.0,20.0,55.0,25.0,25.0,30.0,metapod,72.0,7.0,99.0,1.0,909.0,36%
3,electric,None,101.0,60.0,50.0,70.0,80.0,80.0,150.0,electrode,172.0,12.0,666.0,1.0,737.0,42.5%
4,dark,grass,1001.0,85.0,85.0,100.0,95.0,135.0,70.0,wo-chien,285.0,15.0,742.0,1.0,669.0,44.6%

## 5. Análisis de datos

En esta sección, utilice el DataFrame procesado en la sección anterior, `clean_df`, para responder las siguientes preguntas con texto y/o código.

#### 5.1 ¿Cuántas combinaciones de tipos (`type1` y `type2`) existen en su dataset? ¿Cuál es la combinación más común? (4 pts.)

Considere las combinaciones "simétricas" como dos combinaciones diferentes. Por ejemplo,`type1 = bug` y `type2 = water` **no es lo mismo que** `type1 = water` y `type2 = bug`.

In [ ]:
# Respuesta

#### 5.2 ¿Existen pokemones para todas las posibles combinaciones de tipos? Si no es así, mencione un ejemplo de combinación que no existe en su dataset. Justifique su respuesta con código (3 pts.)

In [ ]:
# Respuesta

#### 5.3 Use la función entregada `get_column_avg_by_type()` y responda  (6 pts.):

* ¿Cuál es el tipo de pokemon más popular? Imprima el tipo y el valor promedio de popularidad.
* ¿Cuál es el tipo de pokemon más veloz? Imprima el tipo y el valor promedio de velocidad.
* ¿Cuál es el tipo de pokemon con mayor defensa? Imprima el tipo y el valor promedio de defensa.

In [ ]:
def get_column_avg_by_type(df: pd.DataFrame, column: str) -> pd.DataFrame:
    """
    (NO MODIFICAR)
    Retorna un DataFrame con el promedio de dicha columna agrupado por tipo de Pokémon.
    """
    all_types = df['type1'].unique()
    dfs_by_type = [clean_df[(clean_df['type1'] == t) | (clean_df['type2'] == t)] for t in all_types]
    avg_column = {t: df_t[column].mean() for t, df_t in zip(all_types, dfs_by_type)}
    return pd.DataFrame(avg_column.items(), columns=['type', f'avg_{column}'])

Respuesta:

In [ ]:
# Respuesta
get_column_avg_by_type(clean_df, 'popularity')

TypeError: Could not convert string '72.8%70.7%44.6%46.1%38%52.5%40%40.5%56.2%58.9%49%52.8%58.7%60%62%56.2%52.1%41%50.7%35.2%41.1%69.5%69.3%64.5%66.7%67.7%53.5%42.8%56.6%41.1%41.4%47.2%51.5%64.7%55.7%45.8%45.8%37.2%40.5%58.4%65.7%47.2%70.8%43.9%58.7%29.2%35.3%43%52%33%60.9%44%40.6%43.2%65%57.2%40.9%72.1%70.5%68.5%58%40.7%36.1%29.9%44.4%57.1%47%26.8%45%53.3%53%48.2%55%48.5%60.9%34.6%42.7%41.8%40.8%63.6%54.3%72%57.7%53.5%51.1%51.6%68.2%40.9%59.8%66.2%64%64.1%46.3%67.8%52.6%55.7%57.5%49%41.5%56.5%45.9%39.3%73.2%67.6%61.3%38.7%55.7%44.3%55.6%44.3%32.7%36.8%48.8%50.1%64.4%54.8%36.6%36.8%48%49.4%22.1%36.1%18.1%28.7%34.3%48.4%46.3%' to numeric

#### 5.4 Muestre la relación entre la velocidad y defensa para pokemon de tipos "Electric" y "Rock" por separado. ¿Cómo se diferencian los stats mencionados en estos dos tipos? (5 pts.)

Para esto, realice un scatterplot que muestre estas dos variables solamente para estos dos tipos de pokemon. 
Recuerde colocarle título, nombre de ejes y etiquetas a su gráfico según corresponda. Además, recuerde que en el gráfico se debe poder diferenciar un tipo de otro. Puede utilizar la librería de visualización que le acomode.

In [ ]:
# Respuesta